spring.application.name=batch
spring.datasource.url=jdbc:postgressql://localhost/dogs
spring.datasource.userame=myuser
spring.datasource.password=secret

spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always